# docker-compose.yml
version: '3.8'

services:
  cms-backend:
    build: .
    container_name: cms-backend
    ports:
      - "3001:3001"
    volumes:
      # 挂载 SSH 私钥（必须！）
      - ./ssh/id_rsa_hexo:/root/.ssh/id_rsa_hexo:ro
      # 挂载hexo项目
      - /var/cms/repos:/app/repos
    environment:
      #  时区（可选，覆盖默认 Asia/Shanghai）
      - TZ=Asia/Shanghai

      #  Git 用户名和邮箱
      - GIT_USER_NAME=bright chen
      - GIT_USER_EMAIL=1024347104@qq.com

      #  可选：自定义 SSH 命令（如需调试可加 -v）
      - GIT_SSH_COMMAND=ssh -i /root/.ssh/id_rsa_hexo -o IdentitiesOnly=yes

      #  可选：自定义 known_hosts 扫描主机
      - SSH_KNOWN_HOSTS=github.com gitee.com

      #  你的业务环境变量
      - ACCESS_TOKEN=12345
      - HEXO_GIT_REPO=git@gitee.com:BrightChenGit/hexo.git
      - HEXO_GIT_BRANCH=master
      # - REDIS_URL=redis://redis:6379/0  # 未来扩展
    restart: unless-stopped
    # depends_on:
    #   - redis