
# docker-compose.yml
version: '3.8'

services:
  cms-backend:
    build: .
    container_name: cms-backend
    ports:
      - "3001:3001"
    volumes:
      # 挂载 SSH 私钥（必须！） 自定义私钥为名为 id_rsa_hexo  :ro 只读
      - ./ssh/id_rsa_hexo:/root/.ssh/id_rsa_hexo:ro
      # 挂载hexo项目
      - /usr/repos:/usr/repos
    environment:
      #  时区（可选，覆盖默认 Asia/Shanghai）
      - TZ=Asia/Shanghai

      #  Git 用户名和邮箱
      - GIT_USER_NAME=HexoAutoDeploy
      - GIT_USER_EMAIL=deploy@myblog.com

      #  可选：自定义 SSH 命令（如需调试可加 -v） SSH 私钥 用于身份认证
      - GIT_SSH_COMMAND=ssh -i /root/.ssh/id_rsa_hexo -o IdentitiesOnly=yes

      #  可选：自定义 known_hosts 扫描主机
      - SSH_KNOWN_HOSTS=github.com gitee.com

      #  你的业务环境变量
      - ACCESS_TOKEN=your_secret_token_here
      - HEXO_GIT_REPO=git@github.com:yourname/your-hexo-repo.git
      - HEXO_GIT_BRANCH=master
      # - REDIS_URL=redis://redis:6379/0  # 未来扩展
    restart: unless-stopped
    # depends_on:
    #   - redis